
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${{ secrets.MYSQL_HOST }}:3307/wanted_saving?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: ${{ secrets.MYSQL_USERNAME}}
    password: ${{ secrets.MYSQL_PASSWORD}}

jwt:
  secret: ${{ secrets.JWT_SECRET_KEY}}
  expired-ms: ${{ secrets.JWT_EXPIRED_MS}}

#logging:
#  level:
#    com.saving: debug

webhook:
  api:
    url: ${{ secrets.WEBHOOK_API_URL}}